## Health Check
GET http://localhost:5000/api/health

### ดูสินค้าทั้งหมด
GET http://localhost:5000/api/products

### ดูสินค้าแนะนำ
GET http://localhost:5000/api/products/featured

### สมัครสมาชิก
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "lastName": "User",
  "email": "realtest@test.com",
  "password": "123456",
  "phone": "0812315678",
  "birthday": "1990-01-01",
  "avatarUrl": "/images/avatars/default-avatar.png",
  
}

### เข้าสู่ระบบ
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@maipaws.com",
  "password": "123456"
}

### ดูข้อมูลตัวเอง (ต้องใส่ token)
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIs...

### สร้างสินค้าใหม่ (Admin)
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIs...

{
  "name": "อาหารแมว",
  "description": "อาหารแมวแบบเม็ด",
  "price": 350,
  "category": "cat",
  "stock": 100,
  "image": "/images/products/cat-food.jpg"
}

POST http://localhost:5000/api/product


### heathcheck
GET https://pet-shop-express-ujhc.onrender.com/api/health




